export const IMGS = {
  FOTO_PERFIL: '../assets/img/foto-potfolio.png',
  LOGO_ED: '../assets/img/logo_ed.png',
  LOGO_BMS: '../assets/img/logo_bms.png',
  LOGO_GPS: '../assets/img/logo_gps.png',
  LOGO_PMLUZ: '../assets/img/logo_pmluz.png',
  LOGO_ALAIR: '../assets/img/logo_alair.png',
  LOGO_ELITHE: '../assets/img/logo_elithe.png',

  IMG_HTML: '../assets/img/HTML.png',
  IMG_CSS: '../assets/img/CSS.png',
  IMG_SASS: '../assets/img/Sass.png',
  IMG_ANGULAR: '../assets/img/AngularJS.png',
  IMG_JS: '../assets/img/JavaScript.png',
  IMG_TS: '../assets/img/TypeScript.png',
  IMG_NODE: '../assets/img/NodeJs.png',
  IMG_BOOTSTRAP: '../assets/img/Bootstrap.png',
  IMG_JQUERY: '../assets/img/Jquery.png',
  IMG_AZURE: '../assets/img/AzureDevops.png',
  IMG_FIGMA: '../assets/img/Figma.png',
  IMG_GIT: '../assets/img/Git.png',
  IMG_SCRUM: '../assets/img/Scrum.png',
  IMG_POWERBI: '../assets/img/PowerBi.png',
  IMG_ORACLE: '../assets/img/Oracle.png',
  IMG_VBA: '../assets/img/VBA.png',
  IMG_WORDPRESS: '../assets/img/Wordpress.png',
  IMG_JAVA: '../assets/img/Java.png',
}
